name: Test Gemini Action on Issue Comment

on:
  issue_comment:
    types: [created]

jobs:
  run_gemini_action:
    runs-on: ubuntu-latest
    name: Dev Gemini Action
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gemini Action CLI
        uses: ./
        with:
          github-issue-number: ${{ github.event.issue.number }}
          user-question: ${{ github.event.comment.body }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}