name: Gemini Action on PR Comment

on:
  issue_comment:
    types: [created]

jobs:
  run_gemini_action:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
      issues: write
    if: 
      ${{ contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/gemini') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Gemini Action
        uses: ./
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_number: ${{ github.event.issue.number }}
          user_question: ${{ github.event.comment.body }}
          command_restrictions: "pr_code_review,update_pr_with_code,add_suggestion_to_pr,research,update_pr_with_docs"